### ISSUE TITLE
Plugin failed to load in Visual Studio 2019 Preview 1.1

### ISSUE THREAD

**Issue by jessehouwing** [madskristensen/ShowTheShortcut#16]
### Installed product versions
- Visual Studio: 2019 Preview 1.1
- This extension: [example 1.1.21]

### Description
Crash on startup of Visual Studio:

```
  <entry>
    <record>751</record>
    <time>2018/12/14 14:59:07.258</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VSPackage]Source: &apos;ShowTheShortcut&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at ShowTheShortcut.StatusBarInjector.FindStatusBar() in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 56&#x000D;&#x000A;   at ShowTheShortcut.StatusBarInjector..ctor(Window pWindow) in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 20&#x000D;&#x000A;   at ShowTheShortcut.CommandHandler..ctor(DTE2 dte, Options options) in C:\projects\showtheshortcut\src\CommandHandler.cs:line 20&#x000D;&#x000A;   at ShowTheShortcut.CommandHandler.&lt;InitializeAsync&gt;d__15.MoveNext() in C:\projects\showtheshortcut\src\CommandHandler.cs:line 85&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at ShowTheShortcut.VSPackage.&lt;InitializeAsync&gt;d__0.MoveNext() in C:\projects\showtheshortcut\src\VSPackage.cs:line 24&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__65.MoveNext()</description>
    <guid>{9DA28329-F9D5-4F18-91C3-D3285B103D1A}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by jessehouwing** [comment]
Looks like this is caused by the new Start Screen that doesn't show the full Visual Studio window until after the user chooses which solution to open or which repo to clone. Just leaving that screen open will at some point trigger the exception:

![image](https://user-images.githubusercontent.com/4173387/51898321-f699c680-23b0-11e9-83e2-7de4c07f6a86.png)

![image](https://user-images.githubusercontent.com/4173387/51898351-02858880-23b1-11e9-8d81-4ce1be372662.png)

**Comment by RichardD2** [comment]
Same problem with the final release of VS2019.
```
SetSite failed for package [VSPackage]
Source: 'ShowTheShortcut' 
Description: Object reference not set to an instance of an object. 
System.NullReferenceException: 
Object reference not set to an instance of an object. 
  at ShowTheShortcut.StatusBarInjector.FindStatusBar() in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 56
  at ShowTheShortcut.StatusBarInjector..ctor(Window pWindow) in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 20
  at ShowTheShortcut.CommandHandler..ctor(DTE2 dte, Options options) in C:\projects\showtheshortcut\src\CommandHandler.cs:line 20
  at ShowTheShortcut.CommandHandler.<InitializeAsync>d__15.MoveNext() in C:\projects\showtheshortcut\src\CommandHandler.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at ShowTheShortcut.VSPackage.<InitializeAsync>d__0.MoveNext() in C:\projects\showtheshortcut\src\VSPackage.cs:line 24
--- End of stack trace from previous location where exception was thrown --- 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown --- 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
```

**Comment by hzeng-tfs** [comment]
> Looks like this is caused by the new Start Screen that doesn't show the full Visual Studio window until after the user chooses which solution to open or which repo to clone. Just leaving that screen open will at some point trigger the exception:
> 
> ![image](https://user-images.githubusercontent.com/4173387/51898321-f699c680-23b0-11e9-83e2-7de4c07f6a86.png)
> 
> ![image](https://user-images.githubusercontent.com/4173387/51898351-02858880-23b1-11e9-8d81-4ce1be372662.png)

You are right. If you choose one project quickly enough, then you won't see that exception.

**Comment by hzeng-tfs** [comment]
You can make "Continue without code" as default action whenever you startup VS2019 by changing following option:
`Options | Environment | Startup | choose "Empty environment"`

they you won't see this loading exception anymore.
