### ISSUE TITLE
Load error - Visual Studio 2019 Enterprise 16.0.2

### ISSUE THREAD

**Issue by wilhelmmedetz** [madskristensen/ShowTheShortcut#17]
### Installed product versions
- Visual Studio 2019 Enterprise 16.0.2
- This extension: 1.4.35

### Description
Extension does not load.
Error displayed during VS startup.

### Steps to recreate
When disabled the the error disappears.

### Current behavior
VS displays error message box
[ActivityLog.zip](https://github.com/madskristensen/ShowTheShortcut/files/3098603/ActivityLog.zip)

### Expected behavior
Should load.

**Comment by kapsiR** [comment]
I can reproduce this `NullReferenceException` in Visual Studio 16.1.0 too.

> SetSite failed for package 
> 
> [VSPackage]Source: 'ShowTheShortcut';
> Description: Object reference not set to an instance of an object.
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ShowTheShortcut.StatusBarInjector.FindStatusBar() in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 56
>    at ShowTheShortcut.StatusBarInjector..ctor(Window pWindow) in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 20
>    at ShowTheShortcut.CommandHandler..ctor(DTE2 dte, Options options) in C:\projects\showtheshortcut\src\CommandHandler.cs:line 20
>    at ShowTheShortcut.CommandHandler.&lt;InitializeAsync&gt;d__15.MoveNext() in C:\projects\showtheshortcut\src\CommandHandler.cs:line 85
>    
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ShowTheShortcut.VSPackage.&lt;InitializeAsync&gt;d__0.MoveNext() in C:\projects\showtheshortcut\src\VSPackage.cs:line 24
>    
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()
>    
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__68.MoveNext()

**Comment by wilhelmmedetz** [comment]
Meanwhile works for me for Visual Studio 16.0.* and Visual Studio 16.1.0.
Seems to have been caused by some other extension.
